"""empty message

Revision ID: 75698f16c361
Revises: e1082b9df160
Create Date: 2025-10-17 00:16:14.894968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75698f16c361'
down_revision = 'e1082b9df160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('folower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('following_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('folower')
    # ### end Alembic commands ###
